# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        
    ]
