# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160202_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country_name',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
